import { Grupo } from './../entidades/Grupo';
import { Injectable } from '@angular/core';

@Injectable()
export class GrupoService {
    grupos: Array<Grupo>;

    constructor() {
        this.initializeGroups();
    }

    initializeGroups() {
        this.grupos = [
            { imagem: '', nome: 'BASE', codigo: '0102' },
            { imagem: '', nome: 'CAFETEIRA', codigo: '0024' },
            { imagem: '', nome: 'TELEFONE', codigo: '0078' },
            { imagem: '', nome: 'VIDEO-GAME', codigo: '0081' },
            { imagem: '', nome: 'CORTADOR GRAMA', codigo: '0085' },
            { imagem: '', nome: 'CAIXA FERRAMENTA', codigo: '0249' },
            { imagem: '', nome: 'TABLET', codigo: '0077' },
            { imagem: '', nome: 'MAQUINA FAZER PAO', codigo: '0052' },
            { imagem: '', nome: 'AUTOFALANTE', codigo: '0001' },
            { imagem: '', nome: 'ESCADA', codigo: '0086' },
            { imagem: '', nome: 'RADIO PORTATIL', codigo: '0076' },
            { imagem: '', nome: 'COLCHA', codigo: '0189' },
            { imagem: '', nome: 'HOME THEATER', codigo: '0073' },
            { imagem: '', nome: 'AROMAS', codigo: '0297' },
            { imagem: '', nome: 'TORRADEIRA', codigo: '0246' },
            { imagem: '', nome: 'BALCAO LAVANDERIA', codigo: '0329' },
            { imagem: '', nome: 'CHALEIRA', codigo: '0221' },
            { imagem: '', nome: 'MULTIPROCESSADOR', codigo: '0055' },
            { imagem: '', nome: 'MINI GELADEIRA', codigo: '0262' },
            { imagem: '', nome: 'PINTURA', codigo: '0252' },
            { imagem: '', nome: 'CARRINHO PRAIA', codigo: '0330' },
            { imagem: '', nome: 'SANDUICHEIRA', codigo: '0058' },
            { imagem: '', nome: 'FRONHA', codigo: '0193' },
            { imagem: '', nome: 'MOTOSERRA', codigo: '0197' },
            { imagem: '', nome: 'ACESSORIOS', codigo: '0180' },
            { imagem: '', nome: 'BALCAO BANHEIRO', codigo: '0098' },
            { imagem: '', nome: 'ESTOFADO', codigo: '0119' },
            { imagem: '', nome: 'BANHEIRA BEBE', codigo: '0183' },
            { imagem: '', nome: 'MESA JANTAR', codigo: '0122' },
            { imagem: '', nome: 'ESTANTE', codigo: '0118' },
            { imagem: '', nome: 'LIVREIRO', codigo: '0229' },
            { imagem: '', nome: 'BERCO', codigo: '0105' },
            { imagem: '', nome: 'BELICHE', codigo: '0104' },
            { imagem: '', nome: 'CORTADOR CABELO', codigo: '0227' },
            { imagem: '', nome: 'CORTADOR GRAMA', codigo: '0146' },
            { imagem: '', nome: 'SOPRADOR', codigo: '0148' },
            { imagem: '', nome: 'AUTO RADIO', codigo: '0002' },
            { imagem: '', nome: 'BATERIA AUTOMOTIVA', codigo: '0331' },
            { imagem: '', nome: 'PELICULAS', codigo: '0332' },
            { imagem: '', nome: 'ABAJUR', codigo: '0136' },
            { imagem: '', nome: 'CAMERA FOTOGRAFICA', codigo: '0065' },
            { imagem: '', nome: 'FREEZER', codigo: '0043' },
            { imagem: '', nome: 'APARADOR GRAMA', codigo: '0145' },
            { imagem: '', nome: 'TERMICAS', codigo: '0219' },
            { imagem: '', nome: 'BULE', codigo: '0220' },
            { imagem: '', nome: 'TOALHA', codigo: '0191' },
            { imagem: '', nome: 'CARRINHO BEBE', codigo: '0112' },
            { imagem: '', nome: 'CREPE/WAFFER', codigo: '0242' },
            { imagem: '', nome: 'ACESSORIOS PARA FERRAMENTAS', codigo: '0198' },
            { imagem: '', nome: 'VARAL', codigo: '0130' },
            { imagem: '', nome: 'RACK', codigo: '0125' },
            { imagem: '', nome: 'KIT COZINHA', codigo: '0121' },
            { imagem: '', nome: 'JOGO COPOS', codigo: '0273' },
            { imagem: '', nome: 'CAIXA SOM', codigo: '0152' },
            { imagem: '', nome: 'PORTA CERVEJA', codigo: '0320' },
            { imagem: '', nome: 'QUADRICICLO', codigo: '0005' },
            { imagem: '', nome: 'DVD', codigo: '0070' },
            { imagem: '', nome: 'CADEIRA', codigo: '0109' },
            { imagem: '', nome: 'CHIP', codigo: '0069' },
            { imagem: '', nome: 'FOGAO', codigo: '0041' },
            { imagem: '', nome: 'COND. AR', codigo: '0032' },
            { imagem: '', nome: 'QUADROS', codigo: '0014' },
            { imagem: '', nome: 'POLTRONA', codigo: '0124' },
            { imagem: '', nome: 'ALISADOR CABELO', codigo: '0016' },
            { imagem: '', nome: 'CENTRIFUGA ROUPAS', codigo: '0026' },
            { imagem: '', nome: 'PANELA PRESSAO', codigo: '0224' },
            { imagem: '', nome: 'MANTA', codigo: '0192' },
            { imagem: '', nome: 'ESCOVA MODELADORA', codigo: '0169' },
            { imagem: '', nome: 'DEPURADOR', codigo: '0036' },
            { imagem: '', nome: 'VENTILADOR', codigo: '0061' },
            { imagem: '', nome: 'PANELA AVULSA', codigo: '0223' },
            { imagem: '', nome: 'GPS', codigo: '0072' },
            { imagem: '', nome: 'TAMPO COOKTOP', codigo: '0258' },
            { imagem: '', nome: 'SECADOR CABELO', codigo: '0059' },
            { imagem: '', nome: 'MIDI SYSTEM', codigo: '0074' },
            { imagem: '', nome: 'SAIA BOX', codigo: '0194' },
            { imagem: '', nome: 'ROTEADOR', codigo: '0308' },
            { imagem: '', nome: 'CADEIRA BEBE', codigo: '0182' },
            { imagem: '', nome: 'SUPORTE', codigo: '0245' },
            { imagem: '', nome: 'MIXER', codigo: '0053' },
            { imagem: '', nome: 'ALMOFADA', codigo: '0137' },
            { imagem: '', nome: 'MAQUINA COSTURA', codigo: '0051' },
            { imagem: '', nome: 'NOTEBOOK', codigo: '0095' },
            { imagem: '', nome: 'AQUECEDOR', codigo: '0018' },
            { imagem: '', nome: 'PISCINA', codigo: '0009' },
            { imagem: '', nome: 'FRUTEIRA', codigo: '0120' },
            { imagem: '', nome: 'PRANCHA', codigo: '0215' },
            { imagem: '', nome: 'PNEU', codigo: '0326' },
            { imagem: '', nome: 'PARAFUSADEIRA', codigo: '0157' },
            { imagem: '', nome: 'CADEIRA PRAIA', codigo: '0208' },
            { imagem: '', nome: 'LAVADORA PRESSAO', codigo: '0232' },
            { imagem: '', nome: 'MANGUEIRA', codigo: '0150' },
            { imagem: '', nome: 'MOEDORES', codigo: '0263' },
            { imagem: '', nome: 'SABONETE LIQUIDO', codigo: '0300' },
            { imagem: '', nome: 'LIQUIDIFICADOR', codigo: '0050' },
            { imagem: '', nome: 'TRICICLO', codigo: '0004' },
            { imagem: '', nome: 'EQUIPAMENTOS', codigo: '0138' },
            { imagem: '', nome: 'LENCOL', codigo: '0190' },
            { imagem: '', nome: 'SERRA CIRCULAR', codigo: '0160' },
            { imagem: '', nome: 'LIXEIRA', codigo: '0234' },
            { imagem: '', nome: 'TALHERES', codigo: '0133' },
            { imagem: '', nome: 'ACESSORIOS', codigo: '0327' },
            { imagem: '', nome: 'LAVADORA', codigo: '0048' },
            { imagem: '', nome: 'ANTENA', codigo: '0017' },
            { imagem: '', nome: 'CHURRASQUEIRA', codigo: '0241' },
            { imagem: '', nome: 'ACESSORIOS', codigo: '0090' },
            { imagem: '', nome: 'ADEGA VINHO', codigo: '0170' },
            { imagem: '', nome: 'COZINHA', codigo: '0115' },
            { imagem: '', nome: 'ESCRITORIO', codigo: '0200' },
            { imagem: '', nome: 'BANQUETA', codigo: '0100' },
            { imagem: '', nome: 'BICAMA', codigo: '0106' },
            { imagem: '', nome: 'CALHA PROTETORA', codigo: '0110' },
            { imagem: '', nome: 'ESCRIVANINHA', codigo: '0117' },
            { imagem: '', nome: 'CAMA', codigo: '0111' },
            { imagem: '', nome: 'ROUPEIRO', codigo: '0126' },
            { imagem: '', nome: 'COLCHAO', codigo: '0113' },
            { imagem: '', nome: 'CELULAR', codigo: '0068' },
            { imagem: '', nome: 'FERRO ELETRICO', codigo: '0040' },
            { imagem: '', nome: 'ABRIDORES', codigo: '0264' },
            { imagem: '', nome: 'EDREDON', codigo: '0006' },
            { imagem: '', nome: 'FRIGIDEIRA', codigo: '0225' },
            { imagem: '', nome: 'IMPRESSORA', codigo: '0093' },
            { imagem: '', nome: 'FRITADEIRA', codigo: '0045' },
            { imagem: '', nome: 'TELA DVD', codigo: '0247' },
            { imagem: '', nome: 'KIT SACO ASP. PO', codigo: '0325' },
            { imagem: '', nome: 'REFRIGERADOR', codigo: '0057' },
            { imagem: '', nome: 'ASSENTO/BANCO', codigo: '0149' },
            { imagem: '', nome: 'GRILL', codigo: '0046' },
            { imagem: '', nome: 'JOGO JANTA', codigo: '0131' },
            { imagem: '', nome: 'APARELHO GINASTICA', codigo: '0082' },
            { imagem: '', nome: 'COOKTOP', codigo: '0033' },
            { imagem: '', nome: 'ACESSORIOS', codigo: '0243' },
            { imagem: '', nome: 'ACESSORIOS', codigo: '0218' },
            { imagem: '', nome: 'GUARDA SOL', codigo: '0010' },
            { imagem: '', nome: 'BALDE GELO', codigo: '0260' },
            { imagem: '', nome: 'DEPILADOR', codigo: '0035' },
            { imagem: '', nome: 'CRIADO MUDO', codigo: '0116' },
            { imagem: '', nome: 'CADEIRA JARDIM', codigo: '0214' },
            { imagem: '', nome: 'TERMICAS', codigo: '0134' },
            { imagem: '', nome: 'MALA', codigo: '0202' },
            { imagem: '', nome: 'SAPATEIRA', codigo: '0127' },
            { imagem: '', nome: 'ASPIRADOR', codigo: '0019' },
            { imagem: '', nome: 'FORMAS E ASSADEIRAS', codigo: '0272' },
            { imagem: '', nome: 'ESPREMEDOR FRUTAS', codigo: '0038' },
            { imagem: '', nome: 'TRAVESSEIRO', codigo: '0195' },
            { imagem: '', nome: 'TAPETE', codigo: '0015' },
            { imagem: '', nome: 'CAIXA SOM', codigo: '0003' },
            { imagem: '', nome: 'TABUA PASSAR', codigo: '0128' },
            { imagem: '', nome: 'MESA LATERAL E CENTRO', codigo: '0168' },
            { imagem: '', nome: 'SECADORA', codigo: '0060' },
            { imagem: '', nome: 'TECLADO', codigo: '0166' },
            { imagem: '', nome: 'PIPOQUEIRA', codigo: '0294' },
            { imagem: '', nome: 'COBERTOR', codigo: '0187' },
            { imagem: '', nome: 'BEBEDOURO', codigo: '0023' },
            { imagem: '', nome: 'FURADEIRA', codigo: '0087' },
            { imagem: '', nome: 'COIFA DE COZINHA', codigo: '0031' },
            { imagem: '', nome: 'FONE OUVIDO', codigo: '0282' },
            { imagem: '', nome: 'JOGO PANELA', codigo: '0222' },
            { imagem: '', nome: 'COLCHAO INFLAVEL', codigo: '0253' },
            { imagem: '', nome: 'TAMPO PIA', codigo: '0129' },
            { imagem: '', nome: 'ESMERIL', codigo: '0250' },
            { imagem: '', nome: 'CABECEIRA', codigo: '0107' },
            { imagem: '', nome: 'SERRA TICO-TICO', codigo: '0158' },
            { imagem: '', nome: 'ACESSORIOS', codigo: '0276' },
            { imagem: '', nome: 'FORNO', codigo: '0042' },
            { imagem: '', nome: 'BONECOS', codigo: '0175' },
            { imagem: '', nome: 'BRINQUEDOS ELETRICOS', codigo: '0176' },
            { imagem: '', nome: 'FLORES E VERDES', codigo: '0265' },
            { imagem: '', nome: 'MESA JARDIM', codigo: '0213' },
            { imagem: '', nome: 'VASO', codigo: '0172' },
            { imagem: '', nome: 'BATEDEIRA', codigo: '0022' },
            { imagem: '', nome: 'CIRCULADOR', codigo: '0029' },
            { imagem: '', nome: 'MAQUINA DE SORVETE', codigo: '0309' },
            { imagem: '', nome: 'MONITOR', codigo: '0094' },
            { imagem: '', nome: 'BICICLETA', codigo: '0083' },
            { imagem: '', nome: 'TELEVISOR', codigo: '0079' },
            { imagem: '', nome: 'OMELETEIRA', codigo: '0244' },
            { imagem: '', nome: 'BARRACA', codigo: '0007' },
            { imagem: '', nome: 'FRIGOBAR', codigo: '0044' },
            { imagem: '', nome: 'ESTABILIZADOR', codigo: '0092' },
            { imagem: '', nome: 'CARTAO DE PRESENTE', codigo: '0011' },
            { imagem: '', nome: 'COMODA', codigo: '0114' },
            { imagem: '', nome: 'BALCAO FORNO', codigo: '0099' },
            { imagem: '', nome: 'CONJ CHURRASCO', codigo: '0226' },
            { imagem: '', nome: 'ENFEITE', codigo: '0135' },
            { imagem: '', nome: 'BABA ELETRONICA', codigo: '0062' }
        ];
    }
}