import { Grupo } from './../entidades/Grupo';
import { Injectable } from '@angular/core';

@Injectable()
export class GrupoService {
    grupos: Array<Grupo>;

    constructor() {
        this.initializeGroups();
    }

    initializeGroups() {
        this.grupos = [
            { imagem: '', nome: 'Base', codigo: '0102' },
            { imagem: '', nome: 'Cafeteira', codigo: '0024' },
            { imagem: '', nome: 'Telefone', codigo: '0078' },
            { imagem: '', nome: 'Tablet', codigo: '0077' },
            { imagem: '', nome: 'Maquina fazer pão', codigo: '0052' },
            { imagem: '', nome: 'Autofalante', codigo: '0001' },
            { imagem: '', nome: 'Escada', codigo: '0086' },
            { imagem: '', nome: 'Rádio portátil', codigo: '0076' },
            { imagem: '', nome: 'Colcha', codigo: '0189' },
            { imagem: '', nome: 'Home theater', codigo: '0073' },
            { imagem: '', nome: 'Aromas', codigo: '0297' },
            { imagem: '', nome: 'Balcão lavanderia', codigo: '0329' },
            { imagem: '', nome: 'Multiprocessador', codigo: '0055' },
            { imagem: '', nome: 'Mini geladeira', codigo: '0262' },
            { imagem: '', nome: 'Pintura', codigo: '0252' },
            { imagem: '', nome: 'Carrinho Praia', codigo: '0330' },
            { imagem: '', nome: 'Sanduicheira', codigo: '0058' },
            { imagem: '', nome: 'Estofado', codigo: '0119' },
            { imagem: '', nome: 'Banheira bebe', codigo: '0183' },
            { imagem: '', nome: 'Mesa jantar', codigo: '0122' },
            { imagem: '', nome: 'Estante', codigo: '0118' },
            { imagem: '', nome: 'Cortador cabelo', codigo: '0227' },
            { imagem: '', nome: 'Cortador grama', codigo: '0146' },
            { imagem: '', nome: 'Auto rádio', codigo: '0002' },
            { imagem: '', nome: 'Bateria automotiva', codigo: '0331' },
            { imagem: '', nome: 'Peliculas', codigo: '0332' },
            { imagem: '', nome: 'Abajur', codigo: '0136' },
            { imagem: '', nome: 'Freezer', codigo: '0043' },
            { imagem: '', nome: 'APARADOR GRAMA', codigo: '0145' },
            { imagem: '', nome: 'TERMICAS', codigo: '0219' },
            { imagem: '', nome: 'TOALHA', codigo: '0191' },
            { imagem: '', nome: 'CARRINHO BEBE', codigo: '0112' },
            { imagem: '', nome: 'ACESSORIOS PARA FERRAMENTAS', codigo: '0198' },
            { imagem: '', nome: 'VARAL', codigo: '0130' },
            { imagem: '', nome: 'RACK', codigo: '0125' },
            { imagem: '', nome: 'CAIXA SOM', codigo: '0152' },
            { imagem: '', nome: 'FOGAO', codigo: '0041' },
            { imagem: '', nome: 'COND. AR', codigo: '0032' },
            { imagem: '', nome: 'QUADROS', codigo: '0014' },
            { imagem: '', nome: 'ALISADOR CABELO', codigo: '0016' },
            { imagem: '', nome: 'PANELA PRESSAO', codigo: '0224' },
            { imagem: '', nome: 'ESCOVA MODELADORA', codigo: '0169' },
            { imagem: '', nome: 'DEPURADOR', codigo: '0036' },
            { imagem: '', nome: 'VENTILADOR', codigo: '0061' },
            { imagem: '', nome: 'GPS', codigo: '0072' },
            { imagem: '', nome: 'TAMPO COOKTOP', codigo: '0258' },
            { imagem: '', nome: 'SECADOR CABELO', codigo: '0059' },
            { imagem: '', nome: 'CADEIRA BEBE', codigo: '0182' },
            { imagem: '', nome: 'SUPORTE', codigo: '0245' },
            { imagem: '', nome: 'MIXER', codigo: '0053' },
            { imagem: '', nome: 'ALMOFADA', codigo: '0137' },
            { imagem: '', nome: 'NOTEBOOK', codigo: '0095' },
            { imagem: '', nome: 'PISCINA', codigo: '0009' },
            { imagem: '', nome: 'PRANCHA', codigo: '0215' },
            { imagem: '', nome: 'PNEU', codigo: '0326' },
            { imagem: '', nome: 'CADEIRA PRAIA', codigo: '0208' },
            { imagem: '', nome: 'LAVADORA PRESSAO', codigo: '0232' },
            { imagem: '', nome: 'MANGUEIRA', codigo: '0150' },
            { imagem: '', nome: 'SABONETE LIQUIDO', codigo: '0300' },
            { imagem: '', nome: 'LIQUIDIFICADOR', codigo: '0050' },
            { imagem: '', nome: 'LENCOL', codigo: '0190' },
            { imagem: '', nome: 'LIXEIRA', codigo: '0234' },
            { imagem: '', nome: 'TALHERES', codigo: '0133' },
            { imagem: '', nome: 'ACESSORIOS', codigo: '0327' },
            { imagem: '', nome: 'LAVADORA', codigo: '0048' },
            { imagem: '', nome: 'ANTENA', codigo: '0017' },
            { imagem: '', nome: 'COZINHA', codigo: '0115' },
            { imagem: '', nome: 'ESCRITORIO', codigo: '0200' },
            { imagem: '', nome: 'BANQUETA', codigo: '0100' },
            { imagem: '', nome: 'BICAMA', codigo: '0106' },
            { imagem: '', nome: 'CALHA PROTETORA', codigo: '0110' },
            { imagem: '', nome: 'ESCRIVANINHA', codigo: '0117' },
            { imagem: '', nome: 'ROUPEIRO', codigo: '0126' },
            { imagem: '', nome: 'COLCHAO', codigo: '0113' },
            { imagem: '', nome: 'CELULAR', codigo: '0068' },
            { imagem: '', nome: 'FERRO ELETRICO', codigo: '0040' },
            { imagem: '', nome: 'IMPRESSORA', codigo: '0093' },
            { imagem: '', nome: 'FRITADEIRA', codigo: '0045' },
            { imagem: '', nome: 'REFRIGERADOR', codigo: '0057' },
            { imagem: '', nome: 'ASSENTO/BANCO', codigo: '0149' },
            { imagem: '', nome: 'GRILL', codigo: '0046' },
            { imagem: '', nome: 'JOGO JANTA', codigo: '0131' },
            { imagem: '', nome: 'APARELHO GINASTICA', codigo: '0082' },
            { imagem: '', nome: 'DEPILADOR', codigo: '0035' },
            { imagem: '', nome: 'CRIADO MUDO', codigo: '0116' },
            { imagem: '', nome: 'TERMICAS', codigo: '0134' },
            { imagem: '', nome: 'MALA', codigo: '0202' },
            { imagem: '', nome: 'ASPIRADOR', codigo: '0019' },
            { imagem: '', nome: 'FORMAS E ASSADEIRAS', codigo: '0272' },
            { imagem: '', nome: 'ESPREMEDOR FRUTAS', codigo: '0038' },
            { imagem: '', nome: 'TRAVESSEIRO', codigo: '0195' },
            { imagem: '', nome: 'TAPETE', codigo: '0015' },
            { imagem: '', nome: 'TABUA PASSAR', codigo: '0128' },
            { imagem: '', nome: 'PIPOQUEIRA', codigo: '0294' },
            { imagem: '', nome: 'COBERTOR', codigo: '0187' },
            { imagem: '', nome: 'JOGO PANELA', codigo: '0222' },
            { imagem: '', nome: 'COLCHAO INFLAVEL', codigo: '0253' },
            { imagem: '', nome: 'TAMPO PIA', codigo: '0129' },
            { imagem: '', nome: 'CABECEIRA', codigo: '0107' },
            { imagem: '', nome: 'FORNO', codigo: '0042' },
            { imagem: '', nome: 'BRINQUEDOS ELETRICOS', codigo: '0176' },
            { imagem: '', nome: 'FLORES E VERDES', codigo: '0265' },
            { imagem: '', nome: 'VASO', codigo: '0172' },
            { imagem: '', nome: 'CIRCULADOR', codigo: '0029' },
            { imagem: '', nome: 'MONITOR', codigo: '0094' },
            { imagem: '', nome: 'BICICLETA', codigo: '0083' },
            { imagem: '', nome: 'TELEVISOR', codigo: '0079' },
            { imagem: '', nome: 'COMODA', codigo: '0114' },
            { imagem: '', nome: 'ENFEITE', codigo: '0135' },
        ];
    }
}