import { Grupo } from './../entidades/Grupo';
import { Injectable } from '@angular/core';

@Injectable()
export class GrupoService {
    grupos: Array<Grupo>;

    constructor() {
        this.initializeGroups();
    }

    initializeGroups() {
        this.grupos = [
            { imagem: '', nome: 'Base', codigo: '0102' },
            { imagem: '', nome: 'Cafeteira', codigo: '0024' },
            { imagem: '', nome: 'Telefone', codigo: '0078' },
            { imagem: '', nome: 'Tablet', codigo: '0077' },
            { imagem: '', nome: 'Maquina fazer pão', codigo: '0052' },
            { imagem: '', nome: 'Autofalante', codigo: '0001' },
            { imagem: '', nome: 'Escada', codigo: '0086' },
            { imagem: '', nome: 'Rádio portátil', codigo: '0076' },
            { imagem: '', nome: 'Colcha', codigo: '0189' },
            { imagem: '', nome: 'Home theater', codigo: '0073' },
            { imagem: '', nome: 'Aromas', codigo: '0297' },
            { imagem: '', nome: 'Balcão lavanderia', codigo: '0329' },
            { imagem: '', nome: 'Multiprocessador', codigo: '0055' },
            { imagem: '', nome: 'Mini geladeira', codigo: '0262' },
            { imagem: '', nome: 'Pintura', codigo: '0252' },
            { imagem: '', nome: 'Carrinho Praia', codigo: '0330' },
            { imagem: '', nome: 'Sanduicheira', codigo: '0058' },
            { imagem: '', nome: 'Estofado', codigo: '0119' },
            { imagem: '', nome: 'Banheira bebe', codigo: '0183' },
            { imagem: '', nome: 'Mesa jantar', codigo: '0122' },
            { imagem: '', nome: 'Estante', codigo: '0118' },
            { imagem: '', nome: 'Cortador cabelo', codigo: '0227' },
            { imagem: '', nome: 'Cortador grama', codigo: '0146' },
            { imagem: '', nome: 'Auto rádio', codigo: '0002' },
            { imagem: '', nome: 'Bateria automotiva', codigo: '0331' },
            { imagem: '', nome: 'Peliculas', codigo: '0332' },
            { imagem: '', nome: 'Abajur', codigo: '0136' },
            { imagem: '', nome: 'Freezer', codigo: '0043' },
            { imagem: '', nome: 'Aparador grama', codigo: '0145' },
            { imagem: '', nome: 'Termicas', codigo: '0219' },
            { imagem: '', nome: 'Toalha', codigo: '0191' },
            { imagem: '', nome: 'Carrinho bebe', codigo: '0112' },
            { imagem: '', nome: 'Acessórios ferramentas', codigo: '0198' },
            { imagem: '', nome: 'Varal', codigo: '0130' },
            { imagem: '', nome: 'Rack', codigo: '0125' },
            { imagem: '', nome: 'Caixa som', codigo: '0152' },
            { imagem: '', nome: 'Fogão', codigo: '0041' },
            { imagem: '', nome: 'Cond. Ar', codigo: '0032' },
            { imagem: '', nome: 'Quadros', codigo: '0014' },
            { imagem: '', nome: 'Alisador cabelo', codigo: '0016' },
            { imagem: '', nome: 'Panela pressão', codigo: '0224' },
            { imagem: '', nome: 'Escova modeladora', codigo: '0169' },
            { imagem: '', nome: 'Depurador', codigo: '0036' },
            { imagem: '', nome: 'Ventilador', codigo: '0061' },
            { imagem: '', nome: 'Gps', codigo: '0072' },
            { imagem: '', nome: 'Tampo cooktop', codigo: '0258' },
            { imagem: '', nome: 'Secador cabelo', codigo: '0059' },
            { imagem: '', nome: 'Cadeira beb', codigo: '0182' },
            { imagem: '', nome: 'Suporte', codigo: '0245' },
            { imagem: '', nome: 'Mixer', codigo: '0053' },
            { imagem: '', nome: 'Almofada', codigo: '0137' },
            { imagem: '', nome: 'Notebook', codigo: '0095' },
            { imagem: '', nome: 'Piscina', codigo: '0009' },
            { imagem: '', nome: 'Prancha', codigo: '0215' },
            { imagem: '', nome: 'Pneu', codigo: '0326' },
            { imagem: '', nome: 'Cadeira praia', codigo: '0208' },
            { imagem: '', nome: 'Lavadora pressão', codigo: '0232' },
            { imagem: '', nome: 'Mangueira', codigo: '0150' },
            { imagem: '', nome: 'Sabonete liquido', codigo: '0300' },
            { imagem: '', nome: 'Liquidificador', codigo: '0050' },
            { imagem: '', nome: 'Lencol', codigo: '0190' },
            { imagem: '', nome: 'Lixeira', codigo: '0234' },
            { imagem: '', nome: 'Talheres', codigo: '0133' },
            { imagem: '', nome: 'Acessórios', codigo: '0327' },
            { imagem: '', nome: 'Lavadora', codigo: '0048' },
            { imagem: '', nome: 'Antena', codigo: '0017' },
            { imagem: '', nome: 'Cozinha', codigo: '0115' },
            { imagem: '', nome: 'Escritório', codigo: '0200' },
            { imagem: '', nome: 'Banqueta', codigo: '0100' },
            { imagem: '', nome: 'Bicama', codigo: '0106' },
            { imagem: '', nome: 'Calha protetora', codigo: '0110' },
            { imagem: '', nome: 'Escrivaninha', codigo: '0117' },
            { imagem: '', nome: 'Roupeiro', codigo: '0126' },
            { imagem: '', nome: 'Colchão', codigo: '0113' },
            { imagem: '', nome: 'Celular', codigo: '0068' },
            { imagem: '', nome: 'Ferro elétrico', codigo: '0040' },
            { imagem: '', nome: 'Impressora', codigo: '0093' },
            { imagem: '', nome: 'Fritadeira', codigo: '0045' },
            { imagem: '', nome: 'Refrigerador', codigo: '0057' },
            { imagem: '', nome: 'Assento/banco', codigo: '0149' },
            { imagem: '', nome: 'Grill', codigo: '0046' },
            { imagem: '', nome: 'Jogo janta', codigo: '0131' },
            { imagem: '', nome: 'Aparelho ginástica', codigo: '0082' },
            { imagem: '', nome: 'Depilador', codigo: '0035' },
            { imagem: '', nome: 'Criado mudo', codigo: '0116' },
            { imagem: '', nome: 'Térmica', codigo: '0134' },
            { imagem: '', nome: 'Mala', codigo: '0202' },
            { imagem: '', nome: 'Aspirador', codigo: '0019' },
            { imagem: '', nome: 'Formas assadeiras', codigo: '0272' },
            { imagem: '', nome: 'Espremedor frutas', codigo: '0038' },
            { imagem: '', nome: 'Travesseiro', codigo: '0195' },
            { imagem: '', nome: 'Tapete', codigo: '0015' },
            { imagem: '', nome: 'Tabua passar', codigo: '0128' },
            { imagem: '', nome: 'Pipoqueira', codigo: '0294' },
            { imagem: '', nome: 'Cobertor', codigo: '0187' },
            { imagem: '', nome: 'Jogo panela', codigo: '0222' },
            { imagem: '', nome: 'Colchão inflável', codigo: '0253' },
            { imagem: '', nome: 'Tampo pia', codigo: '0129' },
            { imagem: '', nome: 'Cabeceira', codigo: '0107' },
            { imagem: '', nome: 'Forno', codigo: '0042' },
            { imagem: '', nome: 'Brinquedos elétricos', codigo: '0176' },
            { imagem: '', nome: 'Flores e verdes', codigo: '0265' },
            { imagem: '', nome: 'Vaso', codigo: '0172' },
            { imagem: '', nome: 'Circulador', codigo: '0029' },
            { imagem: '', nome: 'Monitor', codigo: '0094' },
            { imagem: '', nome: 'Bicicleta', codigo: '0083' },
            { imagem: '', nome: 'Televisor', codigo: '0079' },
            { imagem: '', nome: 'Comoda', codigo: '0114' },
            { imagem: '', nome: 'Enfeite', codigo: '0135' },
        ];
    }
}